main: fr.discowzombie.xpmanager.XPManager
name: XPManager
author: DiscowZombie
version: 1.0
description: Plugin sous licence MIT.
commands:
    exp:
        description: Gestion de l'experience